server:
  port: 8080
  servlet:
    context-path: /springboot-demo
spring:
  datasource:
    url: jdbc:mysql://192.168.2.2:3306/demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #url: jdbc:sqlserver://192.168.2.2:1433;Databasename=demo
    #username: sa
    #password: 123456
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1
    test-While-Idle: true
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config
  thymeleaf:
    cache: false
    prefix: classpath:/thymeleaf/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
logging:
  level:
     com.*.dao: debug
mybatis:
  mapper-locations: classpath:com/*/dao/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
